### ISSUE TITLE
Start Failed on Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by sergmasis** [tobilg/facebook-events-by-location#10]
I need pointers of what I'm doing wrong (if anything). Used both "NPM package" & "Git" method to install and when I ran the "npm start" command this is what I got:

`> facebook-events-by-location@0.5.3 start /usr/share/nginx/html/fb/facebook-events-by-location`
`> node ./index`

`events.js:72`
  `      throw er; // Unhandled 'error' event`
 `             ^`
`Error: listen EADDRINUSE`
`    at errnoException (net.js:905:11)`
`    at Server._listen2 (net.js:1043:14)`
`    at listen (net.js:1065:10)`
`    at net.js:1147:9`
`   at dns.js:72:18`
`    at process._tickCallback (node.js:448:13)`
 `   at Function.Module.runMain (module.js:499:11)`
`    at startup (node.js:119:16)`
`    at node.js:935:3`

`npm ERR! facebook-events-by-location@0.5.3 start: 'node ./index'`
`npm ERR! Exit status 8`
`npm ERR! `
`npm ERR! Failed at the facebook-events-by-location@0.5.3 start script.`
`npm ERR! This is most likely a problem with the facebook-events-by-location package,`
`npm ERR! not with npm itself.`
`npm ERR! Tell the author that this fails on your system:`
`npm ERR!     node ./index`
`npm ERR! You can get their info via:`
`npm ERR!     npm owner ls facebook-events-by-location`
`npm ERR! There is likely additional logging output above.`
`npm ERR! System Linux 3.19.0-28-generic`
`npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"`
`npm ERR! cwd /usr/share/nginx/html/fb/facebook-events-by-location`
`npm ERR! node -v v0.10.37`
`npm ERR! npm -v 1.4.28`
`npm ERR! code ELIFECYCLE`
`npm ERR! `
`npm ERR! Additional logging details can be found in:`
`npm ERR!     /usr/share/nginx/html/fb/facebook-events-by-location/npm-debug.log`
`npm ERR! not ok code 0`

**Comment by tobilg** [comment]
A EADDRINUSE error means that the port is already in use. It's not a problem with the application.
