### ISSUE TITLE
known limitations

### ISSUE THREAD

**Issue by middlesparrow** [tobilg/facebook-events-by-location#13]
Hello.
This is more a question than a doubt.

In a small town, where 20.000 meters or even less can catch all the places (I think), is it possible that public events are still missing and never get caught?

The event is this:
https://www.facebook.com/events/683882395093823/

and is missing from the final listing.

In view of the known limitations you wrote, I tried different coordinates, also query the server at different times, this event isn't comming up.

**Comment by tobilg** [comment]
This is not something I can influence. As I wrote at https://github.com/tobilg/facebook-events-by-location#known-limitations a greater radius doesn't guarantee more/complete results. 

If you have specific examples, test it directly with the Graph API and check if the results are there
