### ISSUE TITLE
Not working after Facebook Graph API version 2.8

### ISSUE THREAD

**Issue by BigFoppa** [tobilg/facebook-events-by-location#14]
For me this is no longer working. After the recent API update the amount of results are a lot less. No matter what API version you are targeting. Searches for place with query q= or q=* like this:

search?type=place&q=*&center=LAT,LNG&distance=2000&format=json&limit=1000&fields=id

Can you confirm that the same is happening to you? /Big

**Comment by tobilg** [comment]
Thanks for reporting, I'll check it over the weekend. You can also set the Graph API version to use, see https://github.com/tobilg/facebook-events-by-location#query-paramenters

**Comment by BigFoppa** [comment]
Hmm, doesn't work for a normal user access token, but gives a lot of results for an app access token.
But then I suspect rate-limiting will hit sooner with more users.

**Comment by BigFoppa** [comment]
Yeah, I have seen you have added the API version.
But as I said, it doesn't matter what version you use, after 2.8 it doesn't matter what version you use. A normal user access token gives a lot less results.

**Comment by tobilg** [comment]
This project is meant to be used with an app access token, as stated in the readme.

**Comment by BigFoppa** [comment]
You'd better explain that. With a user access token from a Facebook login you are probably less likely to be rate-limited. 
But, now after 2.8 a user access token gives a lot less results.

**Comment by tobilg** [comment]
This project is provided as is, just as a reminder. And, as it's stated, it is to be used with an app access token. I don't need to explain that, other than until now the place search needed to be performed with an app access token. 

There's no info in the FB changelog that this has changed. I will not investigate further into something which is stated as not supported.

**Comment by BigFoppa** [comment]
Oh, sorry, just wanted to make you aware of a platform change. No you don't need to explain anything, just tried to have a discussion. No, the search didn't need to be performed with an app access token previously, but it seams like it has to be now. You previously stated that the use of q=* or q= was not documented, so I didn't think you were so rigid about the Facebook documentation.
Anyway, I wont bother you again. /Big
