### ISSUE TITLE
It actually bring all Public Events?

### ISSUE THREAD

**Issue by kwstasna** [tobilg/facebook-events-by-location#15]
Hello.

I have one question.

Say that i have this  [event](https://www.facebook.com/events/1127073794073405/)

Which is in these coordinates

```
lat:    37.987318
lng:   23.730341
```

If I use scan at distance `9000` perhaps, i dont get the Event, and it's public!

Any idea why?

**Comment by tobilg** [comment]
Because https://github.com/tobilg/facebook-events-by-location#known-limitations

> The /search endpoint "magically" limits the number of results, independent from the distance used (larger distance doesn't guarantee more results)

**Comment by kwstasna** [comment]
I'm trying to understand how can we make it bring them all!!
Because I see events on 24 of this month, but the event is on 23 of the month.
Could you please explain to me with a few words how it's filtering the events?
Thanks a lot for your great work though!!

**Comment by tobilg** [comment]
Thanks, but you can't, as I wrote! Facebook limits the results, and it's unknown how/why they do it. Please remember that this project is only a workaround for a functionality that Facebook discontinued. I cannot work around the limits/problems of Facebook's Graph API.

Try using a lat/lng coordinate which is closer to the events's venue, with a smaller distance (like 1000 or 2000) and check the results.

**Comment by kwstasna** [comment]
Ok I will try it out!
One more quick question. When `Category` is going to be implemented on the json? 😄

**Comment by tobilg** [comment]
Category IS actually implemented, but it's yet missing from the sample JSONs:

https://github.com/tobilg/facebook-events-by-location-core/blob/master/lib/eventSearch.js#L231

**Comment by kwstasna** [comment]
I guess category is the category of the Page that made the Event, right?

**Comment by tobilg** [comment]
It' the category field from the Event itself, see https://github.com/tobilg/facebook-events-by-location-core/blob/master/lib/eventSearch.js#L173 and https://developers.facebook.com/docs/graph-api/reference/event#Reading

**Comment by kwstasna** [comment]
Perfect! Thanks a lot!! :love
