### ISSUE TITLE
Place is missing.

### ISSUE THREAD

**Issue by lozo** [tobilg/facebook-events-by-location#16]
Hello, tnx for this awsome app. I would like to ask if there will be support for place(node) in events. Some events have place node. 

  "end_time": "2017-01-15T00:00:00+0100",
  "name": "ŠVAS",
  "place": {
    "name": "MKC Kolnkišta",
    "location": {
      "city": "xxx",
      "country": "xxxx",
      "latitude": 12.42094,
      "longitude": 12.87109,
      "street": "Ptujskega 5",
      "zip": "2250"
    },
    "id": "448303125220321"
  },

The second question is: Can I use this app on heroku? I uploded it to heroku and it throws error but work fine on my local server.

Best regards

**Comment by tobilg** [comment]
Sorry, but I somehow don't understand your request. You have the location information in the `venue` object, why would you need anything else?

Regarding your Heroku question, I'm very sure that the problem is how you deploy it, not the application itself. As I don't use Heroku, I can't help you with that unfortunately.

**Comment by lozo** [comment]
Sometimes the event location is not happening in venue object but in places. Like this example https://www.facebook.com/events/1627227220636712/  if you se the event  is happening in  (Hotel Mitra Ptuj, Prešernova ulica 6, 2250 Ptuj) diffrent than I get from venue object (Zgornji Velovlek 14A) . This location is saved in place object.

**Comment by tobilg** [comment]
That may be possible. The project uses a different approach, as outlined at https://github.com/tobilg/facebook-events-by-location#basics

* Search for places in the radius of the passed coordinate and distance (/search?type=place&q={query}&center={coordinate}&distance={distance})
* Use the places to query for their events in parallel (/?ids={id1},{id2},{id3},...)
* Unify, filter and sort the results from the parallel calls and return them to the client

**Comment by lozo** [comment]
Tnx for the info. 
The  app didnt work on heroku because of the
 app.set("port", process.env.PORT**0** || 3000); in index.js

When i remove the 0 from the PORT part it started to work. Is this maybe a typo?

**Comment by tobilg** [comment]
Nope, this is intentionally chosen. Why don't you just set `PORT0` instead of changing the code?

**Comment by lozo** [comment]
I'm new to heroku but I think that heroku want process.env.PORT. Heroku dynamically assigns your app a port, so you can't set the port to a fixed number.
