### ISSUE TITLE
Location of the Event

### ISSUE THREAD

**Issue by vrgomes** [tobilg/facebook-events-by-location#17]
Hi, I have found an issue with the location returned by facebook-events-by-location.

There are 2 locations on the Events of Facebook:
1- Location of the Page/Company that create the Event.
2- Location where the Event is going to occur.

The facebook-events-by-location is only looking for the number 1 and not for the 2 (where the event is really going to occur).
For instance, Travel Agency's have their headquarters is a location, but they create events everywhere in the country. If I search for the city where their headquarters is located, the facebook-events-by-location will show me all the events for all the country in locations far way from where I'm searching.
The facebook-events-by-location should look for the number 2 (Location where the event is goig to occur).

Example: https://www.facebook.com/events/1180548435392398
The facebook-events-by-location is returning this on "Coimbra, Portugal" where the headquarters of the company is located, but the event is going to happen on "Torres Novas, Portugal".

Is it possible to do this?

Greetings and thanks =)

**Comment by tobilg** [comment]
I'm aware of that, but I disagree that event 2 should be shown. The reason behind this is that the way the search works, as described in https://github.com/tobilg/facebook-events-by-location#basics

This would mean that if the user searches events around coordinate lat,lng with a radius r, the location data would be overwritten so that the actual event is **outside** the search perimeters...

I don't think this is consistent, so I won't change it. Feel free to fork the project and change it to your needs though.

**Comment by vrgomes** [comment]
Thank you for the fast answer.
Sorry for the double post. 
I will try to understand how the algorithm and Facebook works.

**Comment by tobilg** [comment]
No problem, thanks for reporting it. In general, I'd agree with you regarding the inconsistency, but I just don't think that there is an ideal solution for this.

**Comment by BigFoppa** [comment]
@tobilg Maybe you could deliver both locations and let users choose how or which to use. /Big

**Comment by kwstasna** [comment]
its ok to search through place's latitude and longitude, but since the project is called "facebook-**events**-by-location", imo you should also include the information of the actual location of the event in the json response.  😄

**Comment by tobilg** [comment]
@kwstasna To additionally include the event location would be possible, for sure. My concern is a little bit that it leads to confusion, as the location will eventually not match the search coordinates... Also, it will increase the size of the response JSON unnecessarily if the event location is the same as the place... Hmmm.

**Comment by kwstasna** [comment]
@tobilg I think that now is confusing! For example we have this event.

https://www.facebook.com/events/1943327869248831/

Which takes place at 
```
"place": {
    "name": "Gagarin 205 LIve Music Space",
    "location": {
      "city": "Athens",
      "country": "Greece",
      "latitude": 38.00358,
      "longitude": 23.72173,
      "street": "Λεωφόρος Λιοσίων 205",
      "zip": "10445"
    },
    "id": "130357689715"```

But the organizer is the following

https://www.facebook.com/Studio-24-110338136001237/

```  "location": {
    "city": "Athens",
    "country": "Greece",
    "latitude": 37.9776563,
    "longitude": 23.7098812,
    "street": "Dekeleon 26",
    "zip": "11854"
  },
  "id": "110338136001237"```


About the size of json, i wouldn't do anything at all for it. We got to make some sacrifices ! 🤣

**Comment by tobilg** [comment]
This was implemented in https://github.com/tobilg/facebook-events-by-location-core/tree/0.6.0 Currently, there's a security advisory regarding the dependent modules `tough-cookie`, which is used by `request`.

That's why I will wait with publishing the module to NPM.
