### ISSUE TITLE
Clearer installation instructions

### ISSUE THREAD

**Issue by ignacy130** [tobilg/facebook-events-by-location#21]
I followed NPM installation instructions but got an error after running `npm start`
`npm ERR! enoent ENOENT: no such file or directory, open 'C:\D\Projects\Apps
\Events-Loader\package.json'`
where ` 'C:\D\Projects\Apps\Events-Loader\` is directory I executed `npm install...` in.

After installation directory contains only `node_modules` directory.

Stackoverflow says that I should do something with `express` (installing, initiating) but it is not stated in README. If any extra steps are truly needed than they should be described in README, even if they are obvious for node.js devs. :)

I managed to start the service by cloning repo, running `npm i` and `npm start` as stated in git instructions.

**Comment by tobilg** [comment]
See https://github.com/tobilg/facebook-events-by-location#as-npm-package
