### ISSUE TITLE
Current Events

### ISSUE THREAD

**Issue by dimitrisTheof** [tobilg/facebook-events-by-location#22]
As I tested your tool is really great!

I have a problem with current (active) events. In your query I am using:

var eventsFields = [
"id",
"type",
"name",
"cover.fields(id,source)",
"picture.type(large)",
"description",
"start_time",
"end_time",
"category",
"attending_count",
"declined_count",
"maybe_count",
"noreply_count"
];

var fields = [
"id",
"name",
"about",
"emails",
"cover.fields(id,source)",
"picture.type(large)",
"category",
"category_list.fields(name)",
"location",
"events.fields(" + eventsFields.join(",") + ")"
];

eventsUrl = "https://graph.facebook.com/v" + version + "/" +
		    "?ids=" +{{ids}} +
		     "&access_token=" + {{myAccessToken}} +
		      "&fields=" + fields.join(",") +
		      ".since(" + (new Date().getTime()/1000).toFixed() + ")" +
		      ".until(" + {{tomorrowDate}} + ")";

The .since(...) function I can see that calculates only the start_time of the event.
I tried to use the end_date on .since(...) function but probably not use the correct way.
Is there a way to get in my results and the current events?

**Comment by tobilg** [comment]
I'm sorry, but I don't think I understand what you're trying to do... The default for the events is the current timestamp, based on the assumption that you only want so see current or future events. 

What are you trying to achieve? Also, see https://github.com/tobilg/facebook-events-by-location#query-paramenters

**Comment by dimitrisTheof** [comment]
Hello and thank you for your reply.
I want to see current and future events but if I set on .since() the current timestamp as it is mentioned above, I get only the future events and not the current.
Is there a way to get current and future events?
Thank you

**Comment by tobilg** [comment]
In that case you don't need to set the `since` parameter at all. That's the default.

**Comment by dimitrisTheof** [comment]
Without since I got events from 2014-2017
Is there another way?

**Comment by tobilg** [comment]
Can you please show a sample request URL? I'd like to debug this... Thanks!

**Comment by tobilg** [comment]
Any updates @dimitrisTheof? Thanks
