### ISSUE TITLE
Calendar Samples / Working toward natural language search

### ISSUE THREAD

**Issue by GeorgiaData** [tobilg/facebook-events-by-location#23]
Hi Tobi, could you include links to sample front-end calendars that use the feed? 

I'm specifically interested in filtering via audio with Prebuilt Agents.
https://docs.api.ai/docs/calendar

Google Small Talk api lists the following calendar backends. Does the feed match any of these?

aCalendar
CalenGoo calendar
DigiCal calendar
google calendar
hotmail calendar
jorte calendar

To explore: Natural language integration with Facebook Messenger:
https://docs.api.ai/docs/facebook-integration

**Comment by tobilg** [comment]
No, it doesn't, and I currently have no plans to work on it. Feel free to create a PR if you want to contribute this.
