### ISSUE TITLE
UNABLE_TO_GET_ISSUER_CERT_LOCALLY upon npm start

### ISSUE THREAD

**Issue by jengfad** [tobilg/facebook-events-by-location#26]
Git cloned the repo. Upon running npm start and navigating to the port, I get the error:

{"message":{"name":"RequestError","message":"Error: unable to get local issuer certificate","cause":{"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"},"error":{"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"},"options":{"uri":"https://graph.facebook.com/v2.7/search?type=place&q=&center=40.710803,-73.964040&distance=100&limit=100&fields=id&access_token=APP_ACCESS_TOKEN","method":"GET","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}},"code":-1}

**Comment by tobilg** [comment]
You should remove your access token from the pasted code. Are you behind a firewall? Can you access the URL shown / the graph API directly?

**Comment by jengfad** [comment]
I can access the actual grapi-api directly and via httpClient using dotnet core.

**Comment by tobilg** [comment]
I've never seen this error, nor was there ever an issue before. I highly doubt that it's a problem of this project.

See https://github.com/nodejs/node/issues/3742

**Comment by jengfad** [comment]
Will try to run the project on another machine. I'll keep you posted.

**Comment by jengfad** [comment]
Just tried out the project on my home laptop and it now works. I'm thinking that our company firewall has something to do with the error I've encountered yesterday. Closing this issue now.
