### ISSUE TITLE
Site information missing

### ISSUE THREAD

**Issue by SinaAfshar** [tobilg/facebook-events-by-location#27]
Hey, First off thanks for the code it works great!! I noticed however that the site or ticket_uri isn't returned in the metadata. I was wondering how I could bring that into the equation!!

Thanks a lot,

**Comment by tobilg** [comment]
Not sure what you mean to be honest. Can you elaborate?

**Comment by SinaAfshar** [comment]
so you know how the Json returns the name of the event, the address, time ... i noticed that it doesn't however return the site for the event which on facebook's API is listed as ticket_uri. I was wondering if it would be possible to find the site for the individual events.

**Comment by tobilg** [comment]
The `ticket_uri` is not really related to the venue (what you seem to call site), so I'm a bit confused what you are requesting here. See https://developers.facebook.com/docs/graph-api/reference/v2.10/event

The venue information is already contained in the event search response on an event level.

**Comment by tobilg** [comment]
Closing it now, please reopen when you have more details.

**Comment by kwstasna** [comment]
Ticket_uri is the url that users can buy tickets for the event.
it would be great to see it on json response !

**Comment by tobilg** [comment]
Feel free to create an issue with a feature request @kwstasna

**Comment by tobilg** [comment]
@kwstasna Have a look at https://github.com/tobilg/facebook-events-by-location/releases/tag/0.8.0

**Comment by kwstasna** [comment]
Hey thanks a lot for the update !!
I would love to contribute about it but i'm away from laptop/pc 😞
Great work though !
