### ISSUE TITLE
How to grab public events attached to organizers rather than venues?

### ISSUE THREAD

**Issue by rtroncy** [tobilg/facebook-events-by-location#28]
Let's imagine I want to collect public Facebook events located in St Barthelemy island. I could use the following parameter: lat=17.89618; lon=-62.84978; distance=30000

I noticed that [this Facebook event](https://www.facebook.com/events/747141195463451/) will **not** be collected. This event references accurately the location (https://www.facebook.com/EdenRockStBarths/) but strangely, this event is not listed in this venue (https://www.facebook.com/pg/EdenRockStBarths/events/) while it is listed in the organizer events page (https://www.facebook.com/pg/grantcardonefan/events/). Is it the reason why your service does not collect it?

Is this also a limitation of your service? Do you know how to also collect those events? Or is it just that the Facebook graph is not complete when doing backlinks?

**Comment by tobilg** [comment]
It's not querying events by organizers, but from venues/places. The process is explained at https://github.com/tobilg/facebook-events-by-location/blob/master/README.md#basics

**Comment by rtroncy** [comment]
Right, I got this. But this event is taking place to a venue/place which is an object in the Facebook graph.

**Comment by tobilg** [comment]
The Graph API Explorer doesn't show any events in October for the respective place:

https://developers.facebook.com/tools/explorer/?method=GET&path=1433153813602099%2Fevents%3Fsince%3D1506816000&version=v2.10

```javascript
{
  "data": [
  ]
}
```

As outlined, the service first queries the places, and then the events of these places. There's nothing else that can be done here.
