### ISSUE TITLE
Your missing some of your found places

### ISSUE THREAD

**Issue by BigFoppa** [tobilg/facebook-events-by-location#3]
Hi,
You have found a very interesting and useful way of finding events based on location. Thanks for showing it openly.

I found that you are missing some of your places.
In index.js on line 101 you have this code:

      //Create array of 50 places each
      data.forEach(function(idObj, index, arr) {
        if (tempArray.length < idLimit) {
          tempArray.push(idObj.id);
        } else {
          ids.push(tempArray);
          tempArray = [];
        }
      });

      return ids;

That misses every 50th place and what is left in tempArray when the loop is done. I rewrote it like this:

          //Create array of 50 places each
          data.forEach(function (idObj, index, arr) {
            tempArray.push(idObj.id);
              if (tempArray.length >= idLimit) {
                ids.push(tempArray);
                tempArray = [];
              }
          });
          if (tempArray.length > 0) {
            ids.push(tempArray);
          }
          return ids;

Keep up the good work  //Big

**Comment by tobilg** [comment]
Thanks for the report of this bug. I just fixed it with https://github.com/tobilg/facebook-events-by-location/releases/tag/0.4.1 and pushed the new version to NPM.
