### ISSUE TITLE
Finds only few events of all existing

### ISSUE THREAD

**Issue by AqlaSolutions** [tobilg/facebook-events-by-location#30]
With search

http://localhost:3000/events?lat=50.4501&lng=30.5234&distance=50000&accessToken=...&since=7-09-2017&until=8-09-2017

I expect to see all events in my city but it shows only a few.

**Comment by tobilg** [comment]
See https://github.com/tobilg/facebook-events-by-location#known-limitations

> The /search endpoint "magically" limits the number of results, independent from the distance used (larger distance doesn't guarantee more results)

and you're also not using the right syntax for the `since` and `until` parameters, see https://github.com/tobilg/facebook-events-by-location#query-paramenters

**Comment by AqlaSolutions** [comment]
@tobilg, this returns only 10-20 events, it's not nearly close to a real count when I search manually. It makes the app not usable for me at all.

Also `since` and `last` values are in `strtotime` format.

**Comment by tobilg** [comment]
Well, it clearly states that the project is a workaround for a no longer existing FB Graph API functionality. Also, the docs say that FB limit the results, and that larger distances don't guarantee more results.

http://localhost:3000/events?lat=50.4501&lng=30.5234&distance=1000&accessToken=... for example yields around 100 more places than http://localhost:3000/events?lat=50.4501&lng=30.5234&distance=5000&accessToken=... This is not an error or limitation from this project, but from the FB Graph API search.
