### ISSUE TITLE
Query by Facebook category

### ISSUE THREAD

**Issue by c1p81** [tobilg/facebook-events-by-location#31]
Thanks for your work
i would like to ask if it's possible to filter the events also by Facebook category

Thanks
Luca

**Comment by tobilg** [comment]
No, there's currently no such functionality. The FB APIs do not offer to filter on category, which means that the filter would have to be implemented in https://github.com/tobilg/facebook-events-by-location-core after it received the Graph API results...

PR are welcome!

**Comment by c1p81** [comment]
Thanks for the quick reply
i'm sorry but i'm not english ...what means PR ??

**Comment by tobilg** [comment]
PR means pull request. You can have a look here for a description: https://help.github.com/articles/about-pull-requests/

As a hint, you can also just iterate over the returned JSON and filter in your client application for specific event types, e.g. if you stored your JSON in the the `data` variable and are intersted in the `MUSIC_EVENT` category:

```javascript
let myEvents = [];
data.events.forEach(function (eventObj) {
  if (eventObj.category === "MUSIC_EVENT") {
    myEvents.push(eventObj);
  }
});
```

**Comment by Lukas1Komarek** [comment]
You can use a category filter on [Places Graph](https://developers.facebook.com/docs/places/web/search) in facebook-events-by-location-core to add a parameter to the graph URL. This helped me to increase the number of places returned to get more events in a given radius. But I wonder if every place is assigned to a category.

**Comment by vrgomes** [comment]
Hi everyone.
What about iterate recursively on the places search for all types:
 ARTS_ENTERTAINMENT, EDUCATION, FITNESS_RECREATION, FOOD_BEVERAGE, HOTEL_LODGING, MEDICAL_HEALTH, SHOPPING_RETAIL, TRAVEL_TRANSPORTATION.
Then do the event search.
This should help to increase the number of events that it can find.

Greetings.

**Comment by Lukas1Komarek** [comment]
@vrgomes,  unfortunately, the Facebook data API is not perfect (or buggy as hell). Not all places are assigned to your mentioned top-level categories. I tried this in my hometown and I got different results when searching for places with category parameters and searching places without. 
To get nearly all Places you would have to compare the results to another API, get the delta, then get the Facebook IDs through name + address and finally retrieve facebook places + events again.

**Comment by tobilg** [comment]
Furthermore, it's to note that the category mentioned is a _place_ category, not from the event itself. 

@Lukas1Komarek I don't think it'd be practial to implement a process as you described, because this  would take too much time (and has penalties regarding the rate limit I guess).

**Comment by tobilg** [comment]
@vrgomes I tested specifying all categories to place searches, and specifying no categories at all. The former increased the number or results ~10%, but also returned not just more results, but also about 20-30% _different_ results than using no categories at all, which is strange to me.

I tend to think that it'd make sense to implement the category search (as optional), and leave the default with no categories attached in the query, instead of all.

**Comment by tobilg** [comment]
Implemented in https://github.com/tobilg/facebook-events-by-location/releases/tag/0.9.0

**Comment by vrgomes** [comment]
Hi!
It looks promising. I'm going to test it!
Is it possible to run all the categories + null category and then clean up the duplicates? This should give an increased number of results.

Greetings.
