### ISSUE TITLE
Only a few events are displayed.

### ISSUE THREAD

**Issue by ONataLux** [tobilg/facebook-events-by-location#32]
Hi tobilg,

I am making use of your project for my school project, already many thanks for making this possible, but I have a little problem.

when entering my city coordinates etc etc, I do only receive 2 events in my whole town, which is not possible, Is this normal or am I doing something wrong?

Looking forward for your reply!

Andres

PS: this is the URL I use.

http://localhost:3000/events?lat=50.8718973&lng=5.516716&distance=150&sort=venue&AccesToken=(my token here)

**Comment by tobilg** [comment]
You only have a radius of 150m. Please choose a bigger one and center it in the center of your city.
