### ISSUE TITLE
Get event based on user location

### ISSUE THREAD

**Issue by Rickkorsten** [tobilg/facebook-events-by-location#36]
Can i use it in combination with react native?
And do i need to install the facebook graph API of fbsdk?

**Comment by Rickkorsten** [comment]
@tobilg the docs dont say anything about react-native !!can i use this in combination with React-Native??

**Comment by tobilg** [comment]
What portion of https://github.com/tobilg/facebook-events-by-location/blob/master/README.md#search-facebook-events-by-location-as-a-service is unclear to you? It’s a webservice, to be used as backend. This has nothing to do with React Native.
