### ISSUE TITLE
FYI - Facebook bug report

### ISSUE THREAD

**Issue by BigFoppa** [tobilg/facebook-events-by-location#37]
Hi,
just wanted to make you aware of this bug report:

https://developers.facebook.com/bugs/1964040817254857/

/Big

**Comment by tobilg** [comment]
Thanks for letting me know @BigFoppa! Seems like they broke their API (again)... :-/

**Comment by kwstasna** [comment]
It has been fixed.

**Comment by BigFoppa** [comment]
Yes, it is now fixed. But the game has changed. Back to trial and error...

**Comment by tobilg** [comment]
Any updates @BigFoppa? Shall I close this issue?

**Comment by BigFoppa** [comment]
Yes you can close it. The places search is still giving places outside the distance, but it is not as bad as it was.
Unfortunately a search is now giving less results.

**Comment by vrgomes** [comment]
I'm getting a LOT LESS events.
Is anyone also having this issue?
