### ISSUE TITLE
Always getting back an empty events array

### ISSUE THREAD

**Issue by Ashishopenstack** [tobilg/facebook-events-by-location#46]
**Not a issue but a doubt on the working of the api**
On request to the server I always receive an empty events array. Could there be a particular reason to it.
{
    "events": [],
    "metadata": {
        "venues": 92,
        "venuesWithEvents": 0,
        "events": 0
    }
}
My Query Url:

localhost:3000/events?lat=12.971599&lng=77.594563&accessToken=ACCESS_TOKEN&sort=venue 
My current location is Bangalore where I can see a lot of events occurring in Facebook. Why is the api not able to fetch any of those events.
Thanks

**Comment by tobilg** [comment]
Please have a look at https://github.com/tobilg/facebook-events-by-location#current-fb-issues Currently, FB blocked access to event data via the Graph API.
