### ISSUE TITLE
Usage without local server

### ISSUE THREAD

**Issue by carleryd** [tobilg/facebook-events-by-location#5]
I currently have a script that queries the local server set up with this npm package and store the events in a database. Would it be possible to use this plugin without setting up a local server? It's an unnecessary step which I would like to get around!

**Comment by tobilg** [comment]
This would be possible to do, but would require significant refactoring and probably the creation of a base Facebook event search module.

You should be able to extract the necessary code yourself, have a look at https://github.com/tobilg/facebook-events-by-location/blob/master/routes/index.js#L80 to https://github.com/tobilg/facebook-events-by-location/blob/master/routes/index.js#L189 

These lines contain the main logic to query for events.
