### ISSUE TITLE
Is this searching method still reliable?

### ISSUE THREAD

**Issue by nerton** [tobilg/facebook-events-by-location#7]
I tried the first step, finding all places in a big city. I gave a center and a 20km radius and it only returned a few hundred places (I checked paging too), but surely there are much more than that. Is it possible facebook has changed something recently and not all places are returned in a big radius?

**Comment by tobilg** [comment]
I think you have a misunderstanding here... It searches for places within a radius, and then queries the Graph API to find places which have events in the future. So, "a few hundred" within 20km radius seem perfectly fine to me.

It's all described at https://github.com/tobilg/facebook-events-by-location#known-limitations Furthermore, you can also call the Graph API directly with the call outlined at https://github.com/tobilg/facebook-events-by-location#search-facebook-events-by-location-as-a-service (step 1) and compare the output to the `metadata.venues` number of the output of the service. If you find some concrete error, please open another issue.

**Comment by nerton** [comment]
No misunderstandings. Searching a 20 km radius in a capital city should yield at least 1000-200 places or more, certainly not 300 hundred

**Comment by tobilg** [comment]
As I wrote, the service **returns places with events**! That's a huge difference from places in general! 

Compare it to the Graph API search output, and if you find discrepancies, open an issue with specific examples so that I can check it. Otherwise I won't take any actions.
